### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by Amir-SDSU** [ZacharyHampton/HomeHarvest#17]
Hello,
Thank you very much for this wonderful code. I tested the code with Redfin and is running perfectly. May I request the following additions if possible? I only use Redfin data.
1. The listing_type only supports "sold" and "for_sale". It would be great if "Pending" or "Contingent" properties can also be returned.
2. The for_sale df does not return DAY_ON_MARKET, LATITUDE, and LONGITUDE
3. the sold df does not return SOLD_DATE, LATITUDE, and LONGITUDE. 
Thank you very much in advance for these updates.
Regards,
Amir Ali

**Comment by ZacharyHampton** [comment]
Hey, I'll take a look into these and add that's possible.

**Comment by Amir-SDSU** [comment]
Hello,

Thank you very much for looking into these.

Regards, 
Amir

**Comment by ZacharyHampton** [comment]
I've added these requests. Pending or Contingent will come at a later date.

**Comment by Amir-SDSU** [comment]
Thank you. I believe Days on Market is still missing.
