### ISSUE TITLE
Sold duration

### ISSUE THREAD

**Issue by Amir-SDSU** [ZacharyHampton/HomeHarvest#18]
Hello again,

I just realized that the sold df only returns a few properties. Typically users are interested in the sold properties over the last 3 months, 6 months and one year for analysis. Could you please add this option? In the sold datebase SOLD DATE is missing and perhaps it can be used to retrieve sold properties over the past months.

Also, I was wondering if it would be possible to have more than one location, for example "San Diego", "Ramona" for the location field. This is useful as the city names do not cover the suburb areas and it could be quite useful to be able to state more than one location in the location field.

Thank you very much in advance for adding these to the program.

Regards,
Amir Ali

**Comment by ZacharyHampton** [comment]
On redfin, its sold within 30 days, I will eventually add configuration for this.

**Comment by ZacharyHampton** [comment]
Also, added sold date

**Comment by ZacharyHampton** [comment]
For multiple locations, I think it's best to be done by the user, as if an exception happens, it will not return any data.

**Comment by Amir-SDSU** [comment]
Thank you very much.
