### ISSUE TITLE
School ratings included

### ISSUE THREAD

**Issue by russellaugust** [ZacharyHampton/HomeHarvest#20]
I'm looking through the code to see if there's a way to get the scraper to pull in school information, which is a huge item people are concerned with when looking at homes. I'm not seeing that data represented anywhere.

**Comment by ZacharyHampton** [comment]
I am able to get school data on Realtor.com, is there a specific way you would like it formatted?

**Comment by ZacharyHampton** [comment]
And what information from the school would you want?

**Comment by russellaugust** [comment]
I'd say the important data is school name and school rating, so just as an additional json field would be amazing.
