### ISSUE TITLE
Zillow error message

### ISSUE THREAD

**Issue by Amir-SDSU** [ZacharyHampton/HomeHarvest#26]
Traceback (most recent call last):
    properties: pd.DataFrame = scrape_property(
                               ^^^^^^^^^^^^^^^^
    final_df = _scrape_single_site(location, site_name[0], listing_type, proxy)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    results = site.search()
              ^^^^^^^^^^^^^

    resp.raise_for_status()

    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.zillow.com/homes/recently_sold/92037_rb/

**Comment by Cinmay2014** [comment]
got the same error
