### ISSUE TITLE
0.3 Update

### ISSUE THREAD

**Issue by ZacharyHampton** [ZacharyHampton/HomeHarvest#28]
- [x] Change default site to realtor (and remove changing site in examples, as this will be the main site)
- [x] Radius search (for comps)
- [x] Last X days search for sold listings
- [x] Simplify data points to be similar, perhaps slightly more informational than MLS

**Comment by ZacharyHampton** [comment]
#31

**Comment by ddxv** [comment]
Hello Zachary, I saw that the most recent updates dropped Zillow and RedFin scrapers. Just curious why, were they just too unreliable or was their data usually overlapping realtor?

**Comment by ZacharyHampton** [comment]
> Hello Zachary, I saw that the most recent updates dropped Zillow and RedFin scrapers. Just curious why, were they just too unreliable or was their data usually overlapping realtor?

The realtor data is better, and easier to get at scale. And there is no point in getting the same data from multiple sites when it's mostly all the same.
