### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by hgncom** [ZacharyHampton/HomeHarvest#33]
I was wondering how I can get the photos of the listings? When I try to use the img_src column (like outputted in the excel sheet) it says it doesn't exist. Are the photos not scraped? Any way to add this?

It is odd to me that my excel sheet does show an img_src (and parsed images, like f.e. from https://photos.zillowstatic.com), but next that I am completely unable to find anything about images (nor img_src anywhere in the code).

Thanks!

**Comment by ZacharyHampton** [comment]
Hey, sorry about this, I'll push an update fixing this sometime today.

**Comment by cullenwatson** [comment]
@hgncom are you using an older version? the property_url can direct you to the listing to see the property's images
